# Generated by Django 2.2.3 on 2019-07-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.CharField(max_length=100)),
                ('judul', models.CharField(max_length=100)),
                ('tanggal', models.DateField()),
                ('isi', models.TextField()),
                ('kategori', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VocabsIndo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indo', models.CharField(max_length=50)),
                ('arti', models.TextField()),
                ('related', models.TextField()),
                ('sinonim', models.TextField()),
            ],
        ),
    ]
